<?php

namespace ContainerEoUewxN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DMzh3wsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dMzh3ws' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dMzh3ws'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MainController::HomePage' => ['privates', '.service_locator.c_CjwZa', 'get_ServiceLocator_CCjwZaService', true],
            'App\\Controller\\StarshipApiController::get' => ['privates', '.service_locator.zN9CGC.', 'get_ServiceLocator_ZN9CGC_Service', true],
            'App\\Controller\\StarshipApiController::getCollection' => ['privates', '.service_locator.zN9CGC.', 'get_ServiceLocator_ZN9CGC_Service', true],
            'App\\Controller\\StarshipController::show' => ['privates', '.service_locator.zN9CGC.', 'get_ServiceLocator_ZN9CGC_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MainController:HomePage' => ['privates', '.service_locator.c_CjwZa', 'get_ServiceLocator_CCjwZaService', true],
            'App\\Controller\\StarshipApiController:get' => ['privates', '.service_locator.zN9CGC.', 'get_ServiceLocator_ZN9CGC_Service', true],
            'App\\Controller\\StarshipApiController:getCollection' => ['privates', '.service_locator.zN9CGC.', 'get_ServiceLocator_ZN9CGC_Service', true],
            'App\\Controller\\StarshipController:show' => ['privates', '.service_locator.zN9CGC.', 'get_ServiceLocator_ZN9CGC_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MainController::HomePage' => '?',
            'App\\Controller\\StarshipApiController::get' => '?',
            'App\\Controller\\StarshipApiController::getCollection' => '?',
            'App\\Controller\\StarshipController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MainController:HomePage' => '?',
            'App\\Controller\\StarshipApiController:get' => '?',
            'App\\Controller\\StarshipApiController:getCollection' => '?',
            'App\\Controller\\StarshipController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
