<?php

namespace Container4hDROfd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_BatyoCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.batyo_C' shared service.
     *
     * @return \App\Controller\StarshipRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\StarshipController::show()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\StarshipRepository". Did you forget to add a use statement?');
    }
}
