<?php

namespace Container4hDROfd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fx2Am14Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fx2Am14' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fx2Am14'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', '.errored.batyo_C', NULL, 'Cannot determine controller argument for "App\\Controller\\StarshipController::show()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\StarshipRepository". Did you forget to add a use statement?'],
        ], [
            'repository' => '?',
        ]);
    }
}
