<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEoUewxN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEoUewxN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEoUewxN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEoUewxN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEoUewxN\App_KernelDevDebugContainer([
    'container.build_hash' => 'EoUewxN',
    'container.build_id' => 'bad7b630',
    'container.build_time' => 1712664910,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEoUewxN');
