<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4i5Rb4c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4i5Rb4c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4i5Rb4c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4i5Rb4c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4i5Rb4c\App_KernelDevDebugContainer([
    'container.build_hash' => '4i5Rb4c',
    'container.build_id' => '72cc5fc5',
    'container.build_time' => 1712650086,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4i5Rb4c');
