<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZPCh9Nu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZPCh9Nu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZPCh9Nu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZPCh9Nu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZPCh9Nu\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZPCh9Nu',
    'container.build_id' => 'f68d45c8',
    'container.build_time' => 1712647314,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZPCh9Nu');
